### ISSUE TITLE
UX Issue when using Create

### ISSUE THREAD

**Issue by TagWolf** [SolarLune/masterplan#83] opened 2022-07-14 13:56 UTC
Create windows causes new creations to open under mouse pointer and therefore hidden under the create menu.

This should instead create in the middle of the current screen,

Honestly, if you want the opinion of a UX/UI designer, I would suggest you move all that functionality into a ribbon at the top of the screen and under the main nav menu so that it's easier and faster for the user. Think MS Word type menu ribbon.

If you want I am happy to do a mockup design for you provided you credit me in the credits.

**Comment by SolarLune** [comment] 2022-07-14 16:26
I've seen this bug reported a couple of times, but I'm not able to reproduce it - clicking on any option in the Create menu creates the new card in the center of the screen, or inserts it into a selected stack. Are you on the latest version of MasterPlan?

I do appreciate the idea that a ribbon could be useful, but I feel like ribbons take up a fair amount of screen real estate and could make the program feel claustrophobic. I'll have to think about it some more.

**Comment by SolarLune** [comment] 2022-07-16 16:14
Hello, this should be resolved, so I'll close this issue. I'll keep thinking about ribbons; still not really sure about it. Thanks, though!

**Closed by SolarLune** 2022-07-16 16:14 UTC
